src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AuteurRepository::class)
 */
class Auteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Unique
     */
    private $nom_prenom;

    /**
     * @ORM\Column(type="string", length=1)
     * @Assert\Choice({"F" , "M"})
     */
    private $sexe;

    /**
     * @ORM\Column(type="date")
     * @Assert\Type("DateTime")
     */
    private $date_de_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Country
     */
    private $nationalite;

    /**
     * @ORM\ManyToMany(targetEntity=Livre::class, mappedBy="auteurs")
     */
    private $livres;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(string $nom_prenom): self
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }
    public function __toString()
    {
        return $this->nom_prenom;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres[] = $livre;
            $livre->addAuteur($this);
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        if ($this->livres->removeElement($livre)) {
            $livre->removeAuteur($this);
        }

        return $this;
    }
}

src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=LivreRepository::class)
 */
class Livre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/97[89][- ]?[0-9]{1,5}[- ]?[0-9]+[- ]?[0-9]+[- ]?[0-9]$/")
     */
    private $isbn;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */
    private $nombre_pages;

    /**
     * @ORM\Column(type="date")
     * @Assert\Type("DateTime")
     */
    private $date_de_parution;

    /**
     * @ORM\Column(type="float")
     * @Assert\Range(
     * min=0,
     * max=20,
     * notInRangeMessage = "Must be between {{ min }} and {{max}}")
     */
    private $note;

    /**
     * @ORM\ManyToMany(targetEntity=Auteur::class, inversedBy="livres")
     */
    private $auteurs;

    /**
     * @ORM\ManyToMany(targetEntity=Genre::class, inversedBy="livres")
     */
    private $genres;

    public function __construct()
    {
        $this->auteurs = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNombrePages(): ?int
    {
        return $this->nombre_pages;
    }

    public function setNombrePages(int $nombre_pages): self
    {
        $this->nombre_pages = $nombre_pages;

        return $this;
    }

    public function getDateDeParution(): ?\DateTimeInterface
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(\DateTimeInterface $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getNote(): ?float
    {
        return $this->note;
    }

    public function setNote(float $note): self
    {
        $this->note = $note;

        return $this;
    }
    public function __toString()
    {
        return $this->titre;
    }

    /**
     * @return Collection|Auteur[]
     */
    public function getAuteurs(): Collection
    {
        return $this->auteurs;
    }

    public function addAuteur(Auteur $auteur): self
    {
        if (!$this->auteurs->contains($auteur)) {
            $this->auteurs[] = $auteur;
        }

        return $this;
    }

    public function removeAuteur(Auteur $auteur): self
    {
        $this->auteurs->removeElement($auteur);

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }

}

src/Form/LivreType.php
<?php

namespace App\Form;

use App\Entity\Livre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class LivreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('isbn', null, [
                'label' => 'ISBN 13',
                'attr' => ['class' => 'form-control my-2']
            ])
            ->add('titre', null, [
                'attr' => ['class' => 'form-control my-2']
            ])
            ->add('nombre_pages', null, [
                'label' => 'Nombre de pages',
                'attr' => ['class' => 'form-control my-2']
            ])
            ->add('date_de_parution', DateType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control my-2'],
            ])
            ->add('note', null, [
                'attr' => ['class' => 'form-control my-2']
            ])
            ->add('auteurs', null, [
                'attr' => ['class' => 'form-control my-2']
            ])
            ->add('genres', null, [
                'attr' => ['class' => 'form-control my-2']
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livre::class,
        ]);
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\GenreRepository;
use App\Repository\LivreRepository;
use App\Repository\AuteurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class LivreController extends AbstractController
{
    /**
     * @Route("/", name="livre_index", methods={"GET"})
     */
    public function index(LivreRepository $livreRepository, GenreRepository $genreRepository, AuteurRepository $auteurRepository): Response
    {
        $livres = $livreRepository->findAll();

        return $this->render('livre/index.html.twig', [
            'livres' => $livres,
            'genres' => $genreRepository->findAll(),
            'auteurs' => $auteurRepository->findAll(),
            'dates' => $livreRepository->findDates(),
        ]);
    }

    /**
     * @Route("/livre/new", name="livre_new", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($livre);
            $entityManager->flush();
            $this->addFlash(
                'notice',
                'Le livre a été bien ajouté'
            );

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/livre/{id}", name="livre_show", methods={"GET"})
     */
    public function show(Livre $livre): Response
    {
        return $this->render('livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    /**
     * @Route("/livre/{id}/edit", name="livre_edit", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            $this->addFlash(
                'notice',
                'Le livre a été bien modifié'
            );

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/livre/{id}", name="livre_delete", methods={"POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $livre->getId(), $request->request->get('_token'))) {
            $entityManager->remove($livre);
            $entityManager->flush();
            $this->addFlash(
                'notice',
                'Le livre a été bien supprimé'
            );
        }

        return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
    }


    /**
     * @Route("/livre/chercher/{motCle}", name="livre_chercher", methods={"GET"})
     */
    public function chercher(String $motCle, LivreRepository $livreRepository): Response
    {
        $livres = $livreRepository->findByTitre($motCle);

        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }


    /**
     * @Route("/livre/liste-entre-deux-dates/{dateMin}/{dateMax}")
     */
    public function listeEntreDeuxDates($dateMin, $dateMax, LivreRepository $livreRepository): Response
    {
        $livres = $livreRepository->findBetweenTwoDates(strval($dateMin), strval($dateMax));
        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }

    /**
     * @Route("/livre/liste-par-note/{note}", name="livre_list_by_note", methods={"GET"})
     */
    public function listByNote(LivreRepository $livreRepository, $note): Response
    {
        $livres = $livreRepository->findByNote($note);
        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }

    /**
     * @Route("/livre/liste-par-date/{date}/", name="livre_list_by_date", methods={"GET"})
     */
    public function listByDate(LivreRepository $livreRepository, $date): Response
    {
        $livres = $livreRepository->findByDate($date);
        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }


    /**
     * @Route("/livre/liste-par-auteur/{auteur}/", name="livre_list_by_auteur", methods={"GET"})
     */
    public function listByAuteur(LivreRepository $livreRepository, $auteur): Response
    {
        $livres = $livreRepository->findByAuteur($auteur);
        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }

    /**
     * @Route("/livre/liste-par-genre/{genre}/", name="livre_list_by_genre", methods={"GET"})
     */
    public function listByGenre(LivreRepository $livreRepository, $genre): Response
    {
        $livres =  $livreRepository->findByGenre($genre);

        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }
}

templates/livre/_delete_form.html.twig
<form class="d-inline-block" method="post" action="{{ path('livre_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
<button class="btn btn-danger"><i class="bi bi-trash" style="color:white;font-size:20px;"></i></button></form>

templates/livre/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-primary"><i class="bi bi-pen" style="color:white;font-size:20px;"></i>{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/livre/chercher.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livres
{% endblock %}
{% block stylesheets %}
<style> 
     
 body { 
    background-color:#d4dae0; 
      }   
</style> 
 {% endblock %}
{% block body %}
	{% if livres|length > 0  %}
		<h1 style="text-align: center; font-size:3em;font-weight:600;">Livres</h1>
<div class="container-fluid"> 
    <div class="row justify-content-center"> 
        <div class="col-md-12"> 
            <div class="card">
				<table id="livres" class="table">
					<thead>
						<tr style=" text-align: center; background-color:rgb(66, 163, 207)">
							<th>Isbn</th>
							<th>Titre</th>
							<th>Nombre de pages</th>
							<th>Date de parution</th>
							<th>Note</th>
							<th></th>
						</tr>
					</thead>
					<tbody style="text-align:center">
						{% for livre in livres %}
							<tr>
								<td>{{ livre.isbn }}</td>
								<td>{{ livre.titre }}</td>
								<td>{{ livre.nombrePages }}</td>
								<td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</td>
								<td>{{ livre.note }}</td>
								<td>
									<a class="btn btn-primary" href="{{ path('livre_show', {'id': livre.id}) }}"><i class="bi bi-eye" style="color:white;font-size:20px;"></i></a>
									{% if is_granted('ROLE_ADMIN') %}
										<a class="btn btn-success" href="{{ path('livre_edit', {'id': livre.id}) }}"><i class="bi bi-pen" style="color:white;font-size:20px;"></i></a>
										{{ include('livre/_delete_form.html.twig') }}
									{% endif %}
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>

	{% else %}
		<p class="alert alert-danger">Aucun résultat</p>
	{% endif %}
{% endblock %}

{% block javascripts %}
	<script src="/js/main.js"></script>
{% endblock %}

templates/livre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livre
{% endblock %}

{% block stylesheets %}
<style> 
     
 body { 
    background-color:#d4dae0; 
      }   
</style> 
 {% endblock %}

{% block body %}
<h1 style="text-align: center; font-size:3em;font-weight:700;">Edit Livre</h1>
<div class="row justify-content-center"> 
    <div class="col-md-10">

	{{ include('livre/_form.html.twig', {'button_label': 'Enregistrer'}) }}
	</div>
</div>
{% endblock %}

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livres
{% endblock %}

{% block stylesheets %}
<style> 
     
 body { 
    background-color:#d4dae0; 
      }   
</style> 
 {% endblock %}

{% block javascripts %}
	<script src="/js/main.js"></script>
	<script src="/js/pagination.js"></script>

{% endblock %}

{% block body %}
	<h1 style="text-align: center; font-size:3em;font-weight:700;">Livres</h1>

<div class="row">
<div class="col-sm-2" style="padding:0px 20px 30px 30px; width: 300px; ">

		<div style="margin-bottom: 50px; margin-left: 35px">
				<img src="/logo1.png" width="200px" height="200px">
		</div>
				<form method="POST" onsubmit="list(event)">
					<span>Lister les livres entre deux années 
					</span>
					<input id="dateMin" type="number" class="form-control">
					<input id="dateMax" type="number" class="form-control">
					<button class="btn btn-primary my-2">Lister</button>
				</form>

				<span>Filter selon</span>
				<select class="form-select mt-2" onchange="filtrerParNote(event)">
					<option selected>Note</option>
					{% for i in 0..20 %}
						<option value="{{ i }}">{{ i }}</option>
					{% endfor %}
				</select>
				<select class="form-select mt-2" onchange="filtrerParDate(event)">
					<option selected>Date de publication</option>
					{% for date in dates|sort  %}
						<option value="{{date.date_de_parution|date("m/d/Y")}}">{{date.date_de_parution|date("m/d/Y")}}</option>
					{% endfor %}
				</select>
				<select class="form-select mt-2" onchange="filtrerParAuteur(event)">
					<option selected>Auteur</option>
					{% for auteur in auteurs %}
						<option value="{{auteur.id}}">{{auteur.nomPrenom}}</option>
					{% endfor %}
				</select>
				<select class="form-select mt-2" onchange="filtrerParGenre(event)">
					<option selected>Genre</option>
					{% for genre in genres %}
						<option value="{{genre.id}}">{{genre.nom}}</option>
					{% endfor %}
				</select>
</div>
<div class="col-sm">
    <div class="row">
                <form method="POST" onsubmit="chercher(event)">
				<div class="row g-3 align-items-center">
					<div class="col-auto">
					<input id="motCle" type="text" class="form-control" style="width:450px;"placeholder="Recherche d'un livre">
					</div>
					<div class="col-auto">
					<button class="btn btn-primary my-2">Chercher</button>
					</div>

					<div class="col-auto">
						{% if is_granted('ROLE_ADMIN') %}
					    <a class="btn btn-success" href="{{ path('livre_new') }}">Ajouter</a>
				        {% endif %}
					</div>		
				
				</div>
				</form>
	</div>
	<div class="row">
<div class="container-fluid"> 
    <div class="row justify-content-center"> 
        <div class="col-md-12"> 
{% for message in app.flashes('notice') %}
            <div class="alert alert-primary alert-dismissible fade show" role="alert" style="margin: 0px 70px 10px 40px; ">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                <i class="bi bi-info-circle"></i> {{ message }}
            </div>
{% endfor %}
            <div class="card">

			
			     				
				<table id="livres" class="table ">
					<thead>
						<tr style=" text-align: center; background-color:rgb(66, 163, 207)">
							<th>Isbn</th>
							<th>Titre</th>
							<th>Nombre de pages</th>
							<th>Date de parution</th>
							<th>Note</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						{% for livre in livres %}
							<tr class="asmaa">
								<td>{{ livre.isbn }}</td>
								<td>{{ livre.titre }}</td>
								<td>{{ livre.nombrePages }}</td>
								<td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</td>

								<td>
									<span id="livre-note-{{ livre.id }}">{{ livre.note }}</span>
								</td>


								<td style="width:200px; display:inline-block">
								<a class="btn btn-primary" href="{{ path('livre_show', {'id': livre.id}) }}"><i class="bi bi-eye" style="color:white;font-size:20px;"></i></a>
                                        {% if is_granted('ROLE_ADMIN') %}
                                <a class="btn btn-success" href="{{ path('livre_edit', {'id': livre.id}) }}"><i class="bi bi-pen" style="color:white;font-size:20px;"></i></a>	
										{{ include('livre/_delete_form.html.twig') }}
									{% endif %}
								</td>
							</tr>
						{% else %}
							<tr>
								<td colspan="7">Aucun résultat</td>
							</tr>
						{% endfor %}

					</tbody>
				</table>
			</div>
		</div>
     </div>	

	<div class="row" style="margin-top:20px">
        <div class="clearfix" style="padding-right: 70px">
            <div style="display: flex; justify-content: flex-end; align-content: flex-end;">

                <ul class="pagination">
                    <li id="previous-page"><button style="padding:0px 10px;height: 38px;background-color: #313a43; color: #FFFFFF" href="javascript:void(0)">Précédent</button></li>
                </ul>
            </div>
        </div>
    </div>	

</div>
</div>
</div>
{% endblock %}

templates/livre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Livre
{% endblock %}
{% block stylesheets %}
<style> 
     
 body { 
    background-color:#d4dae0; 
      }   
</style> 
 {% endblock %}

{% block body %}
	<h1 style="text-align: center; font-size:3em;font-weight:700;">Ajouter Livre</h1>
       <div class="row justify-content-center"> 
        <div class="col-md-10"> 

	{{ include('livre/_form.html.twig') }}
</div>
</div>
{% endblock %}

templates/livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre
{% endblock %}

{% block stylesheets %}
<style> 
     
 body { 
    background-color:#d4dae0; 
      }   
</style> 
 {% endblock %}

{% block body %}
<div class="row"> 
	<div class="col-9">
	<h1 style=" text-align: center;">Livre</h1>
	</div>
	<div class="col" style="margin-top: 40px;">
		{% if is_granted('ROLE_ADMIN') %}
		<a class="btn btn-success" href="{{ path('livre_edit', {'id': livre.id}) }}"><i class="bi bi-pen" style="color:white;font-size:20px;"></i></a>

		{{ include('livre/_delete_form.html.twig') }}
	{% endif %}
	</div>
</div>
<div class="container-fluid"> 
    <div class="row justify-content-center"> 
        <div class="col-md-10"> 
            <div class="card"> 
				<table class="table">
					<tbody>
						<tr style=" text-align: center; background-color:rgb(66, 163, 207)">
							<th>Id</th>
							<td>{{ livre.id }}</td>
						</tr>
						<tr>
							<th>Isbn</th>
							<td>{{ livre.isbn }}</td>
						</tr>
						<tr>
							<th>Titre</th>
							<td>{{ livre.titre }}</td>
						</tr>
						<tr>
							<th>Nombre pages</th>
							<td>{{ livre.nombrePages }}</td>
						</tr>
						<tr>
							<th>Date de parution</th>
							<td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</td>
						</tr>
						<tr>
							<th>Note</th>
							<td>{{ livre.note }}</td>
						</tr>
						<tr>
							<th>Genres</th>
							<td>
								{% for genre in livre.genres %}
									<span>
										{{ genre }}
									</span><br>
								{% endfor %}
							</td>
						</tr>
						<tr>
							<th>Auteurs</th>
							<td>
								{% for auteur in livre.auteurs %}
									<span>
										{{ auteur }}
									</span><br>
								{% endfor %}
							</td>
						</tr>
					</tbody>
				</table>
			</div>
	     </div>
	</div>
</div>


{% endblock %}